// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getMedians
Rcpp::NumericVector getMedians(Rcpp::NumericVector const& x, Rcpp::NumericVector const& wt, Rcpp::IntegerVector const& idx);
RcppExport SEXP _rpart_LAD_getMedians(SEXP xSEXP, SEXP wtSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector const& >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(getMedians(x, wt, idx));
    return rcpp_result_gen;
END_RCPP
}
// getGoodnessOMP
Rcpp::NumericVector getGoodnessOMP(Rcpp::NumericVector const& x, Rcpp::NumericVector const& wt, Rcpp::NumericVector const& medians);
RcppExport SEXP _rpart_LAD_getGoodnessOMP(SEXP xSEXP, SEXP wtSEXP, SEXP mediansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type medians(mediansSEXP);
    rcpp_result_gen = Rcpp::wrap(getGoodnessOMP(x, wt, medians));
    return rcpp_result_gen;
END_RCPP
}
// getGoodness
Rcpp::NumericVector getGoodness(Rcpp::NumericVector const& x, Rcpp::NumericVector const& wt, Rcpp::NumericVector const& medians);
RcppExport SEXP _rpart_LAD_getGoodness(SEXP xSEXP, SEXP wtSEXP, SEXP mediansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type medians(mediansSEXP);
    rcpp_result_gen = Rcpp::wrap(getGoodness(x, wt, medians));
    return rcpp_result_gen;
END_RCPP
}
// sort_index
Rcpp::IntegerVector sort_index(Rcpp::NumericVector x);
RcppExport SEXP _rpart_LAD_sort_index(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sort_index(x));
    return rcpp_result_gen;
END_RCPP
}
// wmedian
double wmedian(Rcpp::NumericVector x, Rcpp::NumericVector weight);
RcppExport SEXP _rpart_LAD_wmedian(SEXP xSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(wmedian(x, weight));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rpart_LAD_getMedians", (DL_FUNC) &_rpart_LAD_getMedians, 3},
    {"_rpart_LAD_getGoodnessOMP", (DL_FUNC) &_rpart_LAD_getGoodnessOMP, 3},
    {"_rpart_LAD_getGoodness", (DL_FUNC) &_rpart_LAD_getGoodness, 3},
    {"_rpart_LAD_sort_index", (DL_FUNC) &_rpart_LAD_sort_index, 1},
    {"_rpart_LAD_wmedian", (DL_FUNC) &_rpart_LAD_wmedian, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rpart_LAD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
